# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "462c59f69751f9ef626fc610dd9f056b"
name = "llm"
application_url = "https://supersentimentally-intercommunicable-charolette.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://supersentimentally-intercommunicable-charolette.ngrok-free.dev/auth/callback"
]

[app_proxy]
url = "https://supersentimentally-intercommunicable-charolette.ngrok-free.dev"
subpath = "llms"
prefix = "tools"
